name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el repositorio de código
        uses: actions/checkout@v2
      - name: Instalar JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Construir con Maven
        run: | 
          mvn clean package -DskipTests
          ls target/
      - name: Guardar JAR para despliegue
        uses: actions/upload-artifact@v4
        with:
          name: moviecards-java
          path: '${{ github.workspace }}/target/*.jar'

  probar:
    needs: compilar
    runs-on: ubuntu-latest
    steps:
      - name: probar
        run: echo "Probando"

  controlar_calidad:
    needs: probar
    runs-on: ubuntu-latest
    steps:
      - name: calidad
        run: echo "Calidad"
  
  desplegar:
    needs: controlar_calidad
    runs-on: ubuntu-latest
    steps:
      - name: desplegar
        run: echo "Desplegando"
