name: Mi primera Integración Continua

on: push

jobs:
  compilar:
    runs-on: ubuntu-latest

    steps:
      - name: empaquetar
        run: echo "Empaquetando"

  probar:
    needs: compilar
    runs-on: ubuntu-latest
    steps:
      - name: probar
        run: echo "Probando"

  controlar_calidad:
    needs: probar
    runs-on: ubuntu-latest
    steps:
      - name: calidad
        run: echo "Calidad"
  
  desplegar:
    needs: controlar_calidad
    runs-on: ubuntu-latest
    steps:
      - name: desplegar
        run: echo "Desplegando"
